### ISSUE TITLE
Allow the user to disable the plugin when editing C++

### ISSUE THREAD

**Issue by Unarelith** [LeBarbu/vim-epitech#10]
I love your plugin a lot, but the only thing I don't like is that the plugin is still active when editing C++...

**Comment by gnuletik** [comment]
This may be a bug with a wrong detection of vim filetype, could you provide a simple file example ?

**Comment by Unarelith** [comment]
The problem happens with every cpp file I edit, I see the red line at 81th column, visual tabs, emacs indent, etc...

**Comment by gnuletik** [comment]
Okay, I just figured out why this was happening

The internal CPP plugin of vim loads every C specific files
( [Source 1](http://stackoverflow.com/questions/21339177/vim-ftplugin-executes-c-vim-instead-of-cpp-vim-for-c-files) && [Source 2](http://vi.stackexchange.com/questions/3177/use-single-ftplugin-for-more-than-one-filetype) ).

Here is a temporary fix, I'm looking for something cleaner.
In the file `/usr/share/vim/vim74/ftplugin/cpp.vim`
If you comment this line (with a `"` at the beginning of the line) : 

``` vim
runtime! ftplugin/c.vim ftplugin/c_*.vim ftplugin/c/*.vim
```

It temporary solves the issue.
[File](https://github.com/vim/vim/blob/master/runtime/ftplugin/cpp.vim)

By the way, I don't know if it should really be disabled for cpp files.
@LeBarbu What do you think about it ?

**Comment by Unarelith** [comment]
Ok, thanks.

I think it should be disabled for C++ files since there's no norm for C++, but you can always make it optional.

**Comment by gnuletik** [comment]
However, I guess that this is not possible to do that at "plugin-level".
The only way I see is to set everything on files matching "*.c" instead of using the vim filetype detection.
@casimir do you know a better way ?

**Comment by casimir** [comment]
@Quent42340 can you update and try again?

@GNUletik I made a hotfix (https://github.com/LeBarbu/vim-epitech/commit/4d1ef63be6119df54efa412e99f91ac9c5193069). Hot like in _edited directly on Github_. Be prepared to revert. http://replygif.net/366

**Comment by Unarelith** [comment]
Thanks, it seems to work

**Comment by casimir** [comment]
Ok I'll close the ticket then. Feel free to reopen the ticket if needed.

**Comment by Unarelith** [comment]
Ok, thanks guys

**Comment by casimir** [comment]
@Quent42340 I don't know if you use [vim-plug](https://github.com/junegunn/vim-plug) but when I have a filetype problem I use the [on-demand loading feature](https://github.com/junegunn/vim-plug#on-demand-loading-of-plugins). For exemple, you can selectively load a plugin for c files only.

**Comment by Unarelith** [comment]
Actually, I use Vundle, I don't know if there's an equivalent feature

**Comment by casimir** [comment]
I think not, hence the apparition of more modern alternatives (vim-plug, neobundle, etc). Either way this is a problem you don't have anymore!
