### ISSUE TITLE
Some ideas !

### ISSUE THREAD

**Issue by gnuletik** [LeBarbu/vim-epitech#5]
Add a part in README.md to show how to configure the color of cc bar (the default one is a uggly red one)
- hightlight ColorColumn ctermbg=10

New features ?
- Add git merge marker
- End of line red marker

A part "What next ?" for vim's beginners containing for example :
- Configure your syntax, colors... (link examples)
- vim-plug
- ctrlp
- lightline.vim (powerline ?)
- ucompleteme
- nerdtree
- etc...

**Comment by Le-Bit** [comment]
Keep in mind that the original purpose of the plugin is to allow students to use vim in Epitech. 
In order to stick with the UNIX philosophy, I suggest you do a blog post or a gist or whatever that fit you.
I'll add a link to the readme. 
As for the git marker, I don't know what it does. do you have some screenshots to share ?
And for the ColorColumn, the users must have the choice, I think let the defaults on and why not add a line to the Readme.

**Comment by gnuletik** [comment]
A gist to refer some links to show to students how to begin with vim is a very good idea !
I will try to do it !

About the git merge marker, it's cleaner to use this plugin https://github.com/rhysd/conflict-marker.vim, it was a bad idea, as much as the end of line red marker because it's invasive !

About the ColorColumn configuration, I totally agree that users must have the choice, I'm agree to add a line to the README to inform them !

**Comment by casimir** [comment]
@GNUletik As for the `cc`'s color it's up to your theme, there isn't any configuration about that in this plugin.

About new features, are you looking for something like http://vimawesome.com/plugin/vim-signify?

All about helping beginners could have its place here but in the wiki. A good way to share plugins and tweaks is simply linking your .(n)vimrc online (or dotfile repo, ...)

**Comment by gnuletik** [comment]
Yes, but for a begginer's who doesn't have theme, the default one is red. Anyway, with a theme, there isn't problems.

I was just talking about highlighting merge conflicts markers in git. But the plugin I mentioned before do it !
Thanks for vim-signify, it will be useful !

Okay, it's true that the wiki is a better place ! I will try to put some links to help the beginners (and the more experienced ones) !

**Comment by casimir** [comment]
It would be great having an issue to track wiki advancement listing points to document too. Someone will to make it?

**Comment by gnuletik** [comment]
I posted a new thread, I will edit it to add the page / information you want to add in the wiki.
For now, I posted some links to a wiki page !
https://github.com/LeBarbu/vim-epitech/issues/6

**Comment by casimir** [comment]
:+1:
