### ISSUE TITLE
Getting back to Vim's normal indentation?

### ISSUE THREAD

**Issue by juliencampion** [LeBarbu/vim-epitech#7]
In the description it is written that "you can have emacs indentation only for Epitech's files (having a valid header) with `let g:epi_mode_auto = 1`".

So now my .vimrc looks like:

```
" plugins
call plug#begin('~/.vim/plugged')
Plug 'LeBarbu/vim-epitech'
call plug#end()
" vim-epitech settings
let g:epi_login = 'campio_j'
let g:epi_name = 'Julien Campion'
let g:epi_mode_auto = 1
```

But I wrote a .c file with these settings and it gave me the standard Emacs indentation except for the braces:

``` C
int main(void)
{
  int toto = 2;

  while (toto)
  {
    toto = 0;
  }
  return (0);
}
```

Is there a way to revert back to Vim's default C indentation without uninstalling the plugin?

**Comment by casimir** [comment]
Your snippet looks like the Vim indentation, which is normal if you don't have a valid header. Note that this indentation is barely the same as the Emacs one (braces apart).

Note that Vim can indent lines for you using `=`. If you want to indent the whole file you can even use `gg=G`.

Does this answer your question?

**Comment by gnuletik** [comment]
I agree, the difference between the snippet you gave and the one you get without any configuration is the tabstop option in those files : 

```
./after/ftplugin/c.vim:setlocal softtabstop=8
./after/ftplugin/c.vim:setlocal tabstop=8
```

But it is not part of "vim indentation"

**Comment by juliencampion** [comment]
Oh, I didn't see the g:epi_mode_auto only affected braces. Thanks for the explanation!
